# Site settings
title: Rinbo Consulting
email: info@rinbo-consulting.co.uk
description: > # this means to ignore newlines until "baseurl:"
  A mixture of thoughts on Business Intelligence, MicroStrategy, and IT in general 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.rinbo-consulting.co.uk" # the base hostname & protocol for your site
twitter_username: rinboconsulting
github_username:  rinbo-consulting

# Build settings
markdown: kramdown

include:
  - ".nojekyll"

exclude:
  - ".gitignore"
  - "Rakefile"
  - "Gruntfile.coffee"
  - "node_modules"
  - "package.json"
  - "bower_components"
  - "bower.json"

gems:
  - jekyll-sitemap
